server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: bank-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://BANK-USER-SERVICE
          predicates:
            - Path=/bank-user/**
        - id: account-service
          uri: lb://BANK-ACCOUNT-SERVICE
          predicates:
            - Path=/bank-account/**

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
