server:
  port: 8080

spring:
  application:
    name: bank-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://BANK-USER-SERVICE
          predicates:
            - Path=/bank-user/**
        - id: account-service
          uri: lb://BANK-ACCOUNT-SERVICE
          predicates:
            - Path=/bank-account/**
        - id: statement-service
          uri: lb://BANK-STATEMENT-SERVICE
          predicates:
            - Path=/bank-statement/**

bank:
  serviceRegistry:
    username: serviceregistry
    password: ${PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: 'http://${bank.serviceRegistry.username}:${PASSWORD}@localhost:8761/eureka'
  instance:
    hostname: localhost
